job_environments:
  common_environment: &common_environment
    APP_HOSTPATH: 
    CONTAINER_PREFIX: planet4-cool-technologies
    WP_DB_NAME_PREFIX: planet4-cool-tec_wordpress
    FORCE_ACTIVATE_PLUGINS: false
  develop_environment: &develop_environment
    APP_ENVIRONMENT: development
    APP_HOSTNAME: dev.cooltech.p4.greenpeace.org
    CLOUDSQL_INSTANCE: p4-develop-k8s
    GOOGLE_PROJECT_ID: planet-4-151612
    GCLOUD_CLUSTER: p4-development
    HELM_NAMESPACE: develop
    HELM_RELEASE: planet4-cool-technologies
    NEWRELIC_APPNAME: P4 Cool Technologies Development
    WP_DB_NAME: planet4-cool-tec_wordpress_develop
    WP_STATELESS_BUCKET: planet4-cool-technologies-stateless-develop
  release_build_env: &release_build_env
    GOOGLE_PROJECT_ID: planet4-production
  release_environment: &release_environment
    APP_ENVIRONMENT: staging
    APP_HOSTNAME: stage.cooltech.p4.greenpeace.org
    CLOUDSQL_INSTANCE: planet4-prod
    GCLOUD_CLUSTER: planet4-production
    GOOGLE_PROJECT_ID: planet4-production
    HELM_NAMESPACE: cool-technologies
    HELM_RELEASE: planet4-cool-technologies-release
    NEWRELIC_APPNAME: P4 Cool Technologies Release
    WP_DB_NAME: planet4-cool-tec_wordpress_release
    WP_STATELESS_BUCKET: planet4-cool-technologies-stateless-release
  production_environment: &production_environment
    APP_HOSTNAME: cooltechnologies.org
    CLOUDSQL_INSTANCE: planet4-prod
    GCLOUD_CLUSTER: planet4-production
    GOOGLE_PROJECT_ID: planet4-production
    HELM_NAMESPACE: cool-technologies
    HELM_RELEASE: planet4-cool-technologies-master
    MIN_REPLICA_COUNT: 2
    NEWRELIC_APPNAME: P4 Cool Technologies Production
    WP_DB_NAME: planet4-cool-tec_wordpress_master
    WP_STATELESS_BUCKET: planet4-cool-technologies-stateless